project:
  type: website
  output-dir: docs
  resources:
    - /CNAME
    - /favicon.ico
    - /favicon.svg
    - /profile.jpg
    - /robots.txt
    - /notes/*/og.png
    - /simplex.js

format:
  html:
    theme: none
    minimal: true
    css: style.css
    title-block-style: none
    toc: false
    html-math-method: katex
    include-in-header: head.html
    canonical-url: true
    include-before-body: nav.html

website:
  site-url: https://www.aleixalcacer.com
  title: Aleix Alcacer Sales
  open-graph: true
  twitter-card: true
  search: false
