---
title: "N-dimensional Archetypal Analysis for multivariate data"

format:
  html: default
  arxiv-pdf:
    keep-tex: true
    include-in-header:
      - text: |
          \DeclareMathOperator*{\argmin}{arg\,min}

authors:
  - name: Aleix Alcacer
    email: aalcacer@uji.es
    orcid: 0000-0003-3566-0204
    affiliations:
      - ref: uji
  - name: Irene Epifanio
    email: epifanio@uji.es
    orcid: 0000-0002-6973-311X
    affiliations:
      - ref: uji
affiliations:
  - id: uji
    name: Jaume I University
    department: Department of Mathematics
    city: Castelló de la Plana
    country: Spain

abstract: TODO
keywords:
    - archetypal analysis
    - multivariate analysis
    - tensor decomposition
    - convex optimization
    - non-negative tensor factorization

date: 2023-12-03
---

::: {.content-visible when-format="html"}
$$
\DeclareMathOperator*{\argmin}{arg\,min}
$$
:::

# Introduction

TODO

# Methods

TODO

## Background

TODO

## N-dimensional Archetypal Analysis

Let $\mathcal{X} \in {\mathbb{R}^M}^{I_1 \times \dots \times I_N}$  be a data tensor where $\mathbf{x}_{i_1, \dots ,i_N} \in \mathbb{R}^M$ be its $(i_1, \dots, i_N)$-th entry.

In this scenario, the archetypal tensor $\mathcal{Z} \in {\mathbb{R}^M}^{K_1 \times \dots \times K_N}$ will be defined as convex combinations of the tensor $\mathcal{X}$, i.e. $\mathcal{Z} = \mathcal{X} \times_1 \mathcal{B}^{(1)} \times_2 \dots \times_N \mathcal{B}^{(N)}$ where $\mathcal{B}^{(n)} \in \mathbb{R}^{K_n \times I_n}$ for all $n=1,\dots,N$ are stochastic matrices.  Simultaneously, the tensor $\mathcal{X}$ will be approximated by convex combinations of the archetypal tensor $\mathcal{Z}$, i.e. $\mathcal{X} \simeq \mathcal{Z}\times_1\mathcal{A}^{(1)} \times_2 \dots \times_N \mathcal{A}^{(N)}$ where $\mathcal{A}^{(n)} \in \mathbb{R}^{I_n \times K_n}$ for all $n=1,\dots,N$ are also stochastic matrices.


What has been described above can be expressed as an optimization problem:
\begin{equation}
    \argmin_{\mathcal{B}^{(1)}, \dots, \mathcal{B}^{(N)}, \mathcal{A}^{(1)},\dots, \mathcal{B}^{(N)}} \quad \ell\left(\mathcal{X} | (\mathcal{X} \times_1 \mathcal{B}^{(1)} \times_2 \dots \times_N \mathcal{B}^{(N)})\times_1\mathcal{A}^{(1)} \times_2 \dots \times_N \mathcal{A}^{(N)}\right)
\end{equation}

such that:

- $\ell\left(\mathcal{X}|\tilde{\mathcal{X}}\right)$ should be a loss function.
- $\sum_{k=1}^{K_n} \mathcal{A}^{(n)}_{ki} = 1$ with $\mathcal{A}^{(n)}_{ki} \in [0, 1]$ for each $i=1,\dots, I_n$ and $n=1,\dots,N$.
- $\sum_{i=1}^{I_n} \mathcal{B}^{(n)}_{ik} = 1$ with $\mathcal{B}^{(n)}_{ik} \in [0, 1]$ for each $k=1,\dots, K_n$ and $n=1,\dots,N$.

## Related work

TODO

# Results and discussion

TODO

## Example 1: synthetic data

TODO

## Example 2: real data 1

TODO

## Example 3: real data 2

TODO

# Conclusion and future work

TODO

# Acknowledgements {.unnumbered}

This research was partially supported by the Spanish Ministry of Universities (FPU grant FPU20/01825).

# References {.unnumbered}

::: {.references}
:::
